# Generated by Django 3.2.9 on 2021-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('publishing_date_time', models.DateTimeField()),
                ('thumbnail_URL', models.URLField(max_length=500)),
            ],
        ),
    ]
